version: '3.9'

services:
  account.web:
    image: elwark/account/web:${TAG:-latest}
    container_name: "account_web"
    build:
      context: .
      dockerfile: src/Elwark.Account/Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "5005:80"
