name: account

networks:
  elwark_network:
    external: true

services:
  account.web:
    image: elwark/account/web:${TAG:-latest}
    container_name: "elwark_account_web"
    build:
      context: .
    deploy:
      resources:
        limits:
          memory: 128M
    ports:
      - "5005:80"
    networks:
      - elwark_network
