version: '3.7'

services:

  account.web:
    image: elwark/account/web:${TAG:-latest}
    container_name: "account_web"
    build:
      context: .
      dockerfile: Elwark.Account/Dockerfile
    deploy:
      resources:
        limits:
          memory: 16M
    ports:
      - "5005:80"
