version: '3.7'

services:

  account.web:
    container_name: "account_web"
    image: elwark/account/web:${TAG:-latest}
    build:
      context: .
      dockerfile: Elwark.Account/Dockerfile
    ports:
      - "5005:80"
